const menuData = [
  { id: 1, name: "Serbu", price: 8000, category: "Combo", image: "./" },
  { id: 2, name: "Jumbo", price: 20000, category: "Combo", image: "./" },
  { id: 3, name: "Komplit", price: 25000, category: "Combo", image: "./" },
  { id: 3, name: "Pedas", price: 22000, category: "Combo", image: "./" },
  { id: 4, name: "Bakso Alus", price: 2000, category: "Bakso", image: "./" },
  { id: 5, name: "Bakso Urat", price: 3000, category: "Bakso", image: "./" },
  { id: 6, name: "Bakso Jumbo Urat", price: 6500, category: "Bakso", image: "./" },
  { id: 7, name: "Bakso Jumbo Puyuh", price: 7000, category: "Bakso", image: "./" },
  { id: 8, name: "Bakso Kotak Pedas", price: 8000, category: "Bakso", image: "./" },
  { id: 9, name: "Goreng Panjang", price: 2000, category: "Gorengan", image: "./assets/gorengan/gorengan_panjang.jpg" },
  { id: 10, name: "Goreng Bulat", price: 2000, category: "Gorengan", image: "./assets/gorengan/gorengan_bulat.jpg" },
  { id: 11, name: "Goreng Mekar", price: 2000, category: "Gorengan", image: "./assets/gorengan/basreng_mekar.webp" },
  { id: 12, name: "Goreng Rambutan", price: 2000, category: "Gorengan", image: "./assets/gorengan/basreng_rambutan.jpeg" },
  { id: 13, name: "Mie Kuning", price: 2000, category: "Lainnya", image: "./assets/lainnya/mie_kuning.jpg" },
  { id: 14, name: "Mie Bihun", price: 2000, category: "Lainnya", image: "./assets/lainnya/mie_bihun.jpg" },
  { id: 15, name: "Lontong", price: 2000, category: "Lainnya", image: "./assets/lainnya/lontong.jpg" },
  { id: 16, name: "Siomay", price: 2000, category: "Lainnya", image: "./assets/lainnya/siomay.jpg" },
  { id: 17, name: "Tahu Bakso Putih", price: 2000, category: "Lainnya", image: "./assets/lainnya/tahu_bakso_putih.jpg" },
  { id: 18, name: "Tahu Bakso Coklat", price: 2000, category: "Lainnya", image: "./assets/lainnya/tahu_bakso_coklat.jpg" },
  { id: 19, name: "Nasi Putih", price: 2000, category: "Lainnya", image: "./assets/lainnya/nasi_putih.jpg" },
  { id: 20, name: "Es/Panas Teh Manis", price: 4000, category: "Minuman", image: "./assets/minuman/teh_tawar_manis.jpg" },
  { id: 21, name: "Es/Panas Teh Tawar", price: 3000, category: "Minuman", image: "./assets/minuman/teh_tawar_manis.jpg" },
  { id: 22, name: "Es/Panas Jeruk", price: 7000, category: "Minuman", image: "./assets/minuman/jeruk.jpg" },
  { id: 23, name: "Es/Panas Jeruk Nipis", price: 6500, category: "Minuman", image: "./assets/minuman/jeruk_nipis.jpg" },
];

